# Generated by Django 3.2.18 on 2023-06-23 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Student group', 'verbose_name_plural': 'Students groups'},
        ),
    ]
