# Generated by Django 3.2.18 on 2023-07-05 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('power', models.PositiveSmallIntegerField()),
                ('scheme', models.PositiveSmallIntegerField(choices=[(0, 'в ряд'), (1, 'по контуру')])),
                ('soil', models.PositiveSmallIntegerField(choices=[(1, 'чернозем'), (2, 'супесок'), (3, 'песок'), (4, 'суглинок'), (5, 'глина')])),
                ('climate_zone', models.PositiveSmallIntegerField(choices=[(1, 'первой'), (2, 'второй'), (3, 'третьей'), (4, 'четвертой')])),
            ],
        ),
        migrations.CreateModel(
            name='ResultTask1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.FloatField()),
                ('vertical_length', models.FloatField()),
                ('num_accurate', models.FloatField()),
                ('scheme', models.CharField(max_length=32)),
                ('distance_between', models.FloatField()),
                ('section', models.FloatField()),
                ('length', models.FloatField()),
                ('depth', models.FloatField()),
                ('total_resistance', models.FloatField()),
                ('normative_resistance', models.FloatField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calculus.task1')),
            ],
        ),
    ]
