# Generated by Django 3.2.18 on 2023-07-05 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calculus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task1',
            name='created_at',
        ),
    ]
