# Generated by Django 3.2.18 on 2023-07-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task1',
            name='scheme',
            field=models.PositiveSmallIntegerField(choices=[(0, 'в ряд'), (1, 'по контуру')]),
        ),
        migrations.AlterField(
            model_name='task1',
            name='soil',
            field=models.PositiveSmallIntegerField(choices=[(1, 'первая зона'), (2, 'вторая зона'), (3, 'третья зона'), (4, 'четвертая зона')]),
        ),
    ]
