# Generated by Django 3.2.18 on 2023-07-06 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Calculus', '0002_remove_task1_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.PositiveSmallIntegerField(choices=[(1, 'Y/Yн'), (2, 'Δ/Yн')])),
                ('length', models.IntegerField()),
                ('power', models.IntegerField()),
                ('phase_voltage', models.IntegerField()),
                ('phase_square', models.IntegerField()),
                ('phase_material', models.PositiveSmallIntegerField(choices=[(1, 'алюминий'), (2, 'медь')])),
                ('distance_between_conductors', models.IntegerField()),
                ('amperage_nominal', models.IntegerField()),
                ('type_electro', models.PositiveSmallIntegerField(choices=[(1, 'AB'), (2, 'П')])),
            ],
        ),
        migrations.CreateModel(
            name='ResultTask2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square', models.FloatField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calculus.task2')),
            ],
        ),
    ]
