# Generated by Django 3.2.18 on 2023-07-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculus', '0002_auto_20230704_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task1',
            name='amperage',
        ),
        migrations.AlterField(
            model_name='task1',
            name='power',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
