# Generated by Django 3.2.18 on 2023-07-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculus', '0003_auto_20230704_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task1',
            name='climate_zone',
            field=models.PositiveSmallIntegerField(choices=[(1, 'первая зона'), (2, 'вторая зона'), (3, 'третья зона'), (4, 'четвертая зона')]),
        ),
        migrations.AlterField(
            model_name='task1',
            name='soil',
            field=models.PositiveSmallIntegerField(choices=[(1, 'чернозем'), (2, 'супесок'), (3, 'песок'), (4, 'суглинок'), (5, 'глина')]),
        ),
    ]
