# Generated by Django 3.2.18 on 2023-07-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculus', '0003_resulttask2_task2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task2',
            name='distance_between_conductors',
            field=models.FloatField(),
        ),
    ]
