# Generated by Django 3.2.18 on 2023-07-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculus', '0004_alter_task2_distance_between_conductors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task2',
            name='power',
            field=models.PositiveSmallIntegerField(choices=[(1, 40), (2, 63), (3, 400), (4, 630)]),
        ),
    ]
